apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: django-app-dev
data:
  APP_NAME: "django-app"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  APP_ENV: "dev"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:8000"

  # Database Configuration
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "django_app_db"
  POSTGRES_USER: "postgres"

  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  # Celery Configuration
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
